# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Manutastic
email: 
description: > # this means to ignore newlines until "baseurl:"
  Manu is a developer with a strong eye for design. He writes silly things here sometimes.
baseurl: "/blog" # the subpath of your site, e.g. /blog
production_url: http://manutastic.github.io/blog
BASE_PATH: http://manutastic.com/blog
url: "http://manutastic.com" # the base hostname & protocol for your site
twitter_username: manutastic
github_username:  manutastic
future: true

# Build settings
markdown: kramdown
